### ISSUE TITLE
Difference between index.md and tutorial.md

### ISSUE THREAD

**Issue by vsoch** [wkharold/community#4]
I noticed there are two (highly similar) files in the [singularity-containers-with-cloud-build](https://github.com/wkharold/community/tree/singularity-containers-with-cloud-build/tutorials/singularity-containers-with-cloud-build) folder, tutorial.md and index.md. I'm guessing the index.md has frontend matter so that it renders with a static site render (something like jekyll). What is the difference between these files? I want to make sure I'm looking at the correct one!

**Comment by wkharold** [comment]
tutorial.md is the Cloud Shell version. It has markup in it that will open the editor and place you on the line the doc is referring to. Also, the Cloud Shell button isn't useful when you're running the tutorial, splitting them this way allows us to eliminate the button in the tutorial.

I'm going to rename index.md to README.md so it will show up in the repo.

**Comment by vsoch** [comment]
Great! I'll rename in my PR as well.
