### ISSUE TITLE
Difference between creating builder and using builder?

### ISSUE THREAD

**Issue by vsoch** [wkharold/community#6]
For the first step, the user is instructed to cd into singularity-buildstep and then to (what I interpreted as) build the builder:

```bash
$ gcloud builds submit --config=cloudbuild.yaml --substitutions=_SINGULARITY_VERSION="3.0.2" .
```

This was logical - I saw the standard container building steps that I'd see on my local machine.

But then when it's time to build the julia.def, we cd back into the original folder (with the julia.def) file, and we issue the same command?

```bash
$ gcloud builds submit --config=cloudbuild.yaml --substitutions=_SINGULARITY_VERSION="3.0.2" .
```
Do you have any say in this user interaction / commands? I think it's important to create a clear distinction between "I am building the builder I can use in the future" vs. "I am using the builder to do a build."

**Comment by wkharold** [comment]
Right. The first step is _building the build step_. Which is in fact a Docker container wrapped around the singularity command. The second step builds the actual container as you say. Perhaps the confusion is that both steps use a config file called ```cloudbuild.yaml```. We can call those config files whatever we please to make it more obvious what's going on - this was just me being lazy. Nice catch!

**Comment by vsoch** [comment]
lol! Well guess what I didn't even *notice* there were two different files... /bonk. I'll rename one and add an update to the README.md in the PR.

**Comment by vsoch** [comment]
Okay, just clarified this in the README (and renamed the file). /bonks all around, and glad we fixed this up!
